config/routes.rb
Cuckoo::Application.routes.draw do

  root :to => "timesheet#show"

  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get  'users/new_admin'    => 'users/registrations#new_admin'
    post 'users/create_admin' => 'users/registrations#create_admin'
  end

  resources :users, :except => [:destroy]
  resources :projects, :except => [:show, :destroy]
  resources :tasks, :except => [:show, :destroy]
  resources :time_entries

  patch 'time_entries/:id/finish' => 'time_entries#finish', as: :time_entry_finish

  get 'timesheet/:user_id(/:year/:month/:day)' => 'timesheet#show', as: :timesheet

  get 'reports' => 'reports#new', as: :reports
  post 'reports' => 'reports#view'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/project.rb
class Project < ActiveRecord::Base
  default_scope { order(:name) }

  before_destroy :check_associations_are_empty

  has_many :time_entries

  validates_presence_of :name
  validates_uniqueness_of :name

  #
  # Protected methods.
  #
  protected

  def check_associations_are_empty
    !time_entries.any?
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update]

  before_filter :allow_admin_only

  # GET /projects
  def index
    @projects = Project.all
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/:id/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_url, notice: flash_message(:create_success) }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/:id
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_url, notice: flash_message(:update_success) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find_by_id(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name)
  end

  def flash_message(message)
    super(message, Project)
  end

end

app/views/projects/_form.html.erb
<%= simple_form_for(@project, html: { class: 'form-horizontal' }) do |f| %>

  <%= f.error_notification if f.error_notification %>

  <%= f.input :name, autofocus: true %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<div class="page-header">
  <h1>Projects</h1>
  <%= link_to '<i class="icon-plus"></i> Add New'.html_safe, new_project_path, :class => 'btn btn-large' %>
</div>

<div>
  <strong>
    <%= t('plurals.projects', count: @projects.count) %>
  </strong>
</div>

<br/>

<% if @projects.empty? %>
  <div class="text-center alert alert-info">
    <%= t :no_projects %>
  </div>
<% else %>
  <table class="table table-striped table-list">
    <thead>
      <tr>
        <th>Name</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>

    <% @projects.each do |project| %>

      <tr>

        <td><%= project.name %></td>
        <td>
          <div class="btn-group">
            <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-edit icon-white"></i> Actions
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_project_path(project) %>
              </li>
            </ul>
          </div>
        </td>

      </tr>

    <% end %>

    </tbody>

  </table>
<% end %>

app/views/projects/new.html.erb
<div class="page-header">
  <h1>New Project</h1>
</div>

<%= render 'form' %>