config/routes.rb
Cuckoo::Application.routes.draw do

  root :to => "timesheet#show"

  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get  'users/new_admin'    => 'users/registrations#new_admin'
    post 'users/create_admin' => 'users/registrations#create_admin'
  end

  resources :users, :except => [:destroy]
  resources :projects, :except => [:show, :destroy]
  resources :tasks, :except => [:show, :destroy]
  resources :time_entries

  patch 'time_entries/:id/finish' => 'time_entries#finish', as: :time_entry_finish

  get 'timesheet/:user_id(/:year/:month/:day)' => 'timesheet#show', as: :timesheet

  get 'reports' => 'reports#new', as: :reports
  post 'reports' => 'reports#view'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_footer.html.erb
<footer>

  <div class="container">
    <p class="muted credits">
      <%= link_to 'Cuckoo', 'https://github.com/kauplus/cuckoo' %> by <%= link_to 'Kauplus', 'http://www.kauplus.com/' %> &copy; <%= Date.today.year %>
    </p>
  </div>

</footer>

app/views/layouts/_header.html.erb
<header>


  <!-- Navbar -->
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to 'Cuckoo'.html_safe, 'https://github.com/kauplus/cuckoo', target: '_blank', class: 'brand', rel: 'tooltip', data: { original_title: 'Fork me on GitHub', placement: 'bottom' } %>

        <% if user_signed_in? %>
          <ul class="nav">
            <li<%= ' class="active"'.html_safe if page_scope == :timesheet %>><%= link_to 'Track Time', timesheet_url(current_user.id) %></li>
            <% if current_user.is_admin? %>
              <li<%= ' class="active"'.html_safe if page_scope == :settings %>><%= link_to 'Settings', users_path %></li>
            <% end %>
          </ul>
          <ul class="nav pull-right">
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= gravatar_image_tag(current_user.email, gravatar: { size: 35 }, class: 'gravatar') %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li class="nav-header"><%= current_user.name %></li>
                <li><%= link_to 'My Account', edit_user_path(current_user), tabindex: '-1' %></li>
                <li class="divider"></li>
                <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, tabindex: '-1' %></li>
              </ul>
            </li>
          </ul>
        <% end %>

      </div>
    </div>
  </div>

  <% if user_signed_in? %>
    <!-- Subnav -->
    <div class="subnav subnav-fixed">
      <ul class="nav nav-pills">
        <% if page_scope == :timesheet %>
          <li<%= ' class="active"'.html_safe if ['timesheet','time_entries'].include? controller_name %>><%= link_to 'Track', timesheet_path(current_user.id) %></li>
          <% if current_user.is_admin? %>
            <li<%= ' class="active"'.html_safe if controller_name == 'reports' %>><%= link_to 'Reports', reports_path %></li>
          <% end %>
        <% elsif page_scope == :settings && current_user.is_admin? %>
          <li<%= ' class="active"'.html_safe if controller_name == 'users' %>><%= link_to 'Users', users_path %></li>
          <li<%= ' class="active"'.html_safe if controller_name == 'projects' %>><%= link_to 'Projects', projects_path %></li>
          <li<%= ' class="active"'.html_safe if controller_name == 'tasks' %>><%= link_to 'Tasks', tasks_path %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= generate_title %></title>

    <!-- Styles -->
    <%= stylesheet_link_tag    'application', media: 'all' %>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <%= csrf_meta_tags %>
  </head>
  <body id="<%= controller_name %>">

    <div id="loading" class="hide">
      <div class="progress progress-striped active">
        <div class="bar bar-warning" style="width: 0%;"></div>
      </div>
    </div>

    <div id="wrap">

      <%= render 'layouts/header' %>

      <div id="main">
        <div class="container">

          <% unless notice.blank? %>
            <div class="alert alert-success">
              <a class="close" data-dismiss="alert">×</a>
              <strong>Yeah...</strong> <%= notice %>
            </div>
          <% end %>

          <% unless info.blank? %>
            <div class="alert alert-info">
              <a class="close" data-dismiss="alert">×</a>
              <strong>Shh...</strong> <%= info %>
            </div>
          <% end %>

          <% unless warning.blank? %>
            <div class="alert alert-warning">
              <a class="close" data-dismiss="alert">×</a>
              <strong>Oops...</strong> <%= warning %>
            </div>
          <% end %>

          <% unless alert.blank? %>
            <div class="alert alert-error">
              <a class="close" data-dismiss="alert">×</a>
              <strong>Psst...</strong> <%= alert %>
            </div>
          <% end %>

          <%= yield %>

        </div>
      </div>

    </div>

    <%= render 'layouts/footer' %>


    <!--  Javascripts placed at the end of the document
        so the page loads faster
    ==================================================== -->
    <%= javascript_include_tag 'application' %>
    <%= yield :javascripts %>

    <!--  Hidden modals placed at the end of the document
        so the page loads faster
    ==================================================== -->
    <%= yield :modals %>

  </body>
</html>